name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  provider: ^6.0.5
  go_router: ^14.0.0
  geolocator: ^12.0.0
  flutter_local_notifications: ^17.0.0
  adhan_dart: ^1.1.2
  google_fonts: ^6.2.1
  flutter_compass: ^0.8.0
  permission_handler: ^11.3.1
  timezone: ^0.9.4
  intl: ^0.20.2
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
