// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxzsPYe5x40HXYJtaznzQFnbcY0c6Wv04',
    appId: '1:430801660514:web:d8e7617ec31cd7c1903f3b',
    messagingSenderId: '430801660514',
    projectId: 'sabarapp-9c850',
    authDomain: 'sabarapp-9c850.firebaseapp.com',
    storageBucket: 'sabarapp-9c850.firebasestorage.app',
    measurementId: 'G-N0SHS18N3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpHhqGCjTu1b7ntn7zDJ0rg88DooGNkVI',
    appId: '1:430801660514:android:6de3029751513e5c903f3b',
    messagingSenderId: '430801660514',
    projectId: 'sabarapp-9c850',
    storageBucket: 'sabarapp-9c850.firebasestorage.app',
  );
}
